"""add subtotal and discount to orders

Revision ID: 33c8f0c22a06
Revises: b3a4e2c38b59
Create Date: 2025-12-12 15:59:33.784252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c8f0c22a06'
down_revision: Union[str, Sequence[str], None] = 'b3a4e2c38b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('subtotal_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('orders', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'subtotal_amount')
    # ### end Alembic commands ###
