"""Add estimated_agora_cost to orders

Revision ID: b3a4e2c38b59
Revises: 90aeae2ff34c
Create Date: 2025-12-09 11:23:22.907749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a4e2c38b59'
down_revision: Union[str, Sequence[str], None] = '90aeae2ff34c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('estimated_agora_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'estimated_agora_cost')
    # ### end Alembic commands ###
